---
- name: Set postgres number for uninstall
  ansible.builtin.set_fact:
    maas_postgres_version_number: "{{ maas_postgres_version_number }}"

- name: Setting config dirs for uninstall
  ansible.builtin.set_fact:
    maas_postgres_config_dir: "/etc/postgresql/{{ maas_postgres_version_number }}/main/"

- name: Stop Postgres metrics agent
  ansible.builtin.service:
    name: postgres_exporter
    state: stopped
  when: ansible_facts.services['postgres_exporter.service'] is defined

- name: "Remove PostgreSQL artifacts"
  ansible.builtin.file:
    state: absent
    name: "{{ item }}"
  with_items:
    - /opt/pgsql_check
    - /etc/xinetd.d/pgsql_check
    - /etc/systemd/system/postgres_exporter.service
    - "{{ o11y_postgres_exporter_dir }}"

- name: "Uninstall PostgreSQL and configuration dependencies"
  ansible.builtin.apt:
    name:
      - "{{ maas_postgres_deb_name | default('postgresql-' ~ maas_postgres_version_number) }}"
      - "acl"
      - "python3-psycopg2"
      - "xinetd"
    state: absent
    purge: true
